const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),scoreEl=document.getElementById("score"),highestScoreEl=document.getElementById("highestScore"),statusEl=document.getElementById("status"),startBtn=document.getElementById("startBtn"),restartBtn=document.getElementById("restartBtn"),HIGHEST_SCORE_KEY="eatTheCodeHighestScore",gridSize=20,tileCountX=canvas.width/gridSize,tileCountY=canvas.height/gridSize,colors=["#00ff99","#00ccff","#ffcc00","#ff66cc","#cc99ff","#ff6666","#66ff66","#ffffff"];let codePieces=[],snake=[],food={},direction={x:1,y:0},nextDirection={x:1,y:0},score=0,gameLoop=null,gameSpeed=120,isPlaying=!1;highestScoreEl.textContent=localStorage.getItem(HIGHEST_SCORE_KEY)||0;
async function loadCodePieces(){try{const response=await fetch("./data/code-pieces.json");codePieces=await response.json()}catch(error){statusEl.textContent="Failed to read code-pieces.json";console.error(error)}}
function initGame(){snake=[{x:8,y:10},{x:7,y:10},{x:6,y:10}];direction={x:1,y:0};nextDirection={x:1,y:0};score=0;gameSpeed=120;scoreEl.textContent=0;statusEl.textContent="Ready";createFood();drawGame()}
function startGame(){if(!codePieces.length){statusEl.textContent="Code data is not available yet";return}if(isPlaying)return;isPlaying=!0;statusEl.textContent="Playing";clearInterval(gameLoop);gameLoop=setInterval(updateGame,gameSpeed)}
function restartGame(){clearInterval(gameLoop);isPlaying=!1;initGame();startGame()}
function createFood(){const piece=codePieces[Math.floor(Math.random()*codePieces.length)],color=colors[Math.floor(Math.random()*colors.length)];do{food={x:Math.floor(Math.random()*tileCountX),y:Math.floor(Math.random()*tileCountY),text:piece,color}}while(snake.some(part=>part.x===food.x&&part.y===food.y))}
function updateGame(){direction=nextDirection;const head={x:snake[0].x+direction.x,y:snake[0].y+direction.y};if(head.x<0||head.x>=tileCountX||head.y<0||head.y>=tileCountY||snake.some(part=>part.x===head.x&&part.y===head.y)){endGame();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;scoreEl.textContent=score;createFood();increaseSpeed()}else snake.pop();drawGame()}
function increaseSpeed(){if(score%50===0&&gameSpeed>60){gameSpeed-=10;clearInterval(gameLoop);gameLoop=setInterval(updateGame,gameSpeed)}}
function drawGame(){ctx.clearRect(0,0,canvas.width,canvas.height);drawBackgroundGrid();drawFood();drawSnake()}
function drawBackgroundGrid(){ctx.strokeStyle="rgba(255, 255, 255, 0.04)";ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=gridSize){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=gridSize){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}
function drawSnake(){snake.forEach((part,index)=>{const x=part.x*gridSize,y=part.y*gridSize;ctx.fillStyle=index===0?"#00ff99":"#007744";ctx.fillRect(x+2,y+2,gridSize-4,gridSize-4);ctx.strokeStyle="#b7ffc9";ctx.strokeRect(x+2,y+2,gridSize-4,gridSize-4)})}
function drawFood(){const x=food.x*gridSize,y=food.y*gridSize;ctx.fillStyle=food.color;ctx.font="14px Courier New";ctx.textBaseline="middle";ctx.shadowColor=food.color;ctx.shadowBlur=10;ctx.fillText(food.text,x,y+gridSize/2);ctx.shadowBlur=0}
function endGame(){clearInterval(gameLoop);isPlaying=!1;statusEl.textContent="Game Over";const highestScore=Number(localStorage.getItem(HIGHEST_SCORE_KEY))||0;if(score>highestScore){localStorage.setItem(HIGHEST_SCORE_KEY,score);highestScoreEl.textContent=score;statusEl.textContent="New Highest Score!"}drawGame();ctx.fillStyle="rgba(0, 0, 0, 0.7)";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#ff6666";ctx.font="42px Courier New";ctx.textAlign="center";ctx.fillText("GAME OVER",canvas.width/2,canvas.height/2-20);ctx.fillStyle="#00ff99";ctx.font="22px Courier New";ctx.fillText(`Final Score: ${score}`,canvas.width/2,canvas.height/2+25);ctx.textAlign="left"}
document.addEventListener("keydown",event=>{const{key}=event;if(key==="ArrowUp"&&direction.y!==1)nextDirection={x:0,y:-1};else if(key==="ArrowDown"&&direction.y!==-1)nextDirection={x:0,y:1};else if(key==="ArrowLeft"&&direction.x!==1)nextDirection={x:-1,y:0};else if(key==="ArrowRight"&&direction.x!==-1)nextDirection={x:1,y:0}});
startBtn.addEventListener("click",startGame);
restartBtn.addEventListener("click",restartGame);
loadCodePieces().then(initGame);
