const canvas=document.getElementById("spiderWeb"),ctx=canvas.getContext("2d");let width,height,centerX,centerY,webConfig,interactionTime=0,lastFrameTime=0;const pointer={x:0,y:0,active:!1,energy:0},randomBetween=(min,max)=>min+Math.random()*(max-min),randomInt=(min,max)=>Math.floor(randomBetween(min,max+1));
function createWebConfig(){const cornerAnchors=[{x:0,y:0,baseRotation:0},{x:1,y:0,baseRotation:Math.PI/2},{x:0,y:1,baseRotation:-Math.PI/2},{x:1,y:1,baseRotation:Math.PI}];return{centerOffsetX:randomBetween(-.18,.18),centerOffsetY:randomBetween(-.18,.18),rings:randomInt(10,14),spokes:randomInt(24,32),strokeAlpha:randomBetween(.16,.28),lineWidth:randomBetween(.8,1.4),distortionScale:randomBetween(5,12),distortionPhase:randomBetween(.8,2.4),ringVariance:randomBetween(2,7),cornerWebs:cornerAnchors.filter(()=>Math.random()>.15).map(anchor=>({...anchor,size:randomBetween(120,240),lines:randomInt(7,12),arcs:randomInt(4,7),alpha:randomBetween(.1,.22),rotationJitter:randomBetween(-.18,.18),skewX:randomBetween(.88,1.12),skewY:randomBetween(.88,1.12)}))}}
function resizeCanvas(){width=canvas.width=window.innerWidth;height=canvas.height=window.innerHeight;centerX=width/2+width*webConfig.centerOffsetX;centerY=height/2+height*webConfig.centerOffsetY;drawSpiderWeb(0)}
function getInteractiveOffset(x,y,time,scale=1){if(!pointer.active||pointer.energy<.01)return{x:0,y:0};const dx=x-pointer.x,dy=y-pointer.y,distance=Math.sqrt(dx*dx+dy*dy)||1,radius=180;if(distance>radius)return{x:0,y:0};const falloff=(1-distance/radius)**2,wave=Math.sin(distance*.09-time*.025)*.6+.4,strength=pointer.energy*falloff*wave*scale;return{x:dx/distance*strength,y:dy/distance*strength}}
function drawSpiderWeb(time){ctx.clearRect(0,0,width,height);const maxRadius=Math.sqrt(width*width+height*height)/2,{rings,spokes,strokeAlpha,lineWidth,cornerWebs}=webConfig;ctx.strokeStyle=`rgba(255, 255, 255, ${strokeAlpha})`;ctx.lineWidth=lineWidth;for(let i=0;i<spokes;i++){const angle=Math.PI*2/spokes*i,baseX=centerX+Math.cos(angle)*maxRadius,baseY=centerY+Math.sin(angle)*maxRadius,offset=getInteractiveOffset(baseX,baseY,time,1.1);ctx.beginPath();ctx.moveTo(centerX,centerY);ctx.lineTo(baseX+offset.x,baseY+offset.y);ctx.stroke()}for(let r=1;r<=rings;r++){const radius=maxRadius/rings*r;ctx.beginPath();for(let i=0;i<=spokes;i++){const angle=Math.PI*2/spokes*i,distortion=Math.sin(i*webConfig.distortionPhase+r)*webConfig.distortionScale+Math.cos(r*2.1)*webConfig.ringVariance,currentRadius=radius+distortion,baseX=centerX+Math.cos(angle)*currentRadius,baseY=centerY+Math.sin(angle)*currentRadius,offset=getInteractiveOffset(baseX,baseY,time),x=baseX+offset.x,y=baseY+offset.y;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.closePath();ctx.stroke()}cornerWebs.forEach(cornerWeb=>drawCornerWeb(cornerWeb.x===0?0:width,cornerWeb.y===0?0:height,cornerWeb,time))}
function drawCornerWeb(x,y,cornerWeb,time){const{size,lines,arcs,baseRotation,rotationJitter,alpha,skewX,skewY}=cornerWeb;ctx.save();ctx.translate(x,y);ctx.rotate(baseRotation+rotationJitter);ctx.scale(skewX,skewY);ctx.strokeStyle=`rgba(255, 255, 255, ${alpha})`;ctx.lineWidth=Math.max(.8,webConfig.lineWidth-.15);for(let i=0;i<=lines;i++){const angle=Math.PI/2/lines*i,baseX=Math.cos(angle)*size,baseY=Math.sin(angle)*size,worldX=x+baseX*skewX,worldY=y+baseY*skewY,offset=getInteractiveOffset(worldX,worldY,time,.55);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(baseX+offset.x,baseY+offset.y);ctx.stroke()}for(let r=1;r<=arcs;r++){const radius=size/arcs*r;ctx.beginPath();for(let i=0;i<=lines;i++){const angle=Math.PI/2/lines*i,baseX=Math.cos(angle)*radius,baseY=Math.sin(angle)*radius,worldX=x+baseX*skewX,worldY=y+baseY*skewY,offset=getInteractiveOffset(worldX,worldY,time,.45),px=baseX+offset.x,py=baseY+offset.y;i===0?ctx.moveTo(px,py):ctx.lineTo(px,py)}ctx.stroke()}ctx.restore()}
function animate(timestamp){lastFrameTime||(lastFrameTime=timestamp);interactionTime+=timestamp-lastFrameTime;lastFrameTime=timestamp;pointer.energy*=.94;pointer.energy<.02&&(pointer.energy=0);drawSpiderWeb(interactionTime);window.requestAnimationFrame(animate)}
function handlePointerMove(event){const previousX=pointer.active?pointer.x:event.clientX,previousY=pointer.active?pointer.y:event.clientY,speed=Math.hypot(event.clientX-previousX,event.clientY-previousY);pointer.x=event.clientX;pointer.y=event.clientY;pointer.active=!0;pointer.energy=Math.min(20,Math.max(pointer.energy,5+speed*.4))}
function handlePointerLeave(){pointer.active=!1}
webConfig=createWebConfig();window.addEventListener("resize",resizeCanvas);window.addEventListener("pointermove",handlePointerMove);window.addEventListener("pointerleave",handlePointerLeave);resizeCanvas();window.requestAnimationFrame(animate);
