const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),scoreEl=document.getElementById("score"),highestScoreEl=document.getElementById("highestScore"),livesEl=document.getElementById("lives"),statusEl=document.getElementById("status"),startBtn=document.getElementById("startBtn"),restartBtn=document.getElementById("restartBtn"),HIGHEST_SCORE_KEY="catchToolsHighestScore";let tools=[],fallingTools=[],score=0,lives=3,isPlaying=!1,animationId=null,spawnTimer=null;const player={x:canvas.width/2-55,y:canvas.height-45,width:110,height:22,speed:8,moveLeft:!1,moveRight:!1};highestScoreEl.textContent=localStorage.getItem(HIGHEST_SCORE_KEY)||0;
async function loadTools(){try{const response=await fetch("./data/tools.json");tools=await response.json()}catch(error){statusEl.textContent="Gagal membaca tools.json";console.error(error)}}
function initGame(){fallingTools=[];score=0;lives=3;isPlaying=!1;player.x=canvas.width/2-player.width/2;scoreEl.textContent=score;livesEl.textContent=lives;statusEl.textContent="Ready";drawGame()}
function startGame(){if(tools.length===0){statusEl.textContent="Data tool belum tersedia";return}if(isPlaying)return;isPlaying=!0;statusEl.textContent="Playing";spawnTimer=setInterval(spawnTool,700);gameLoop()}
function restartGame(){clearInterval(spawnTimer);cancelAnimationFrame(animationId);initGame();startGame()}
function spawnTool(){const tool=tools[Math.floor(Math.random()*tools.length)];fallingTools.push({name:tool.name,icon:tool.icon,score:tool.score,x:Math.random()*(canvas.width-40)+20,y:-40,size:34,speed:Math.random()*2+2.5})}
function gameLoop(){updateGame();drawGame();if(isPlaying)animationId=requestAnimationFrame(gameLoop)}
function updateGame(){if(player.moveLeft)player.x-=player.speed;if(player.moveRight)player.x+=player.speed;if(player.x<0)player.x=0;if(player.x+player.width>canvas.width)player.x=canvas.width-player.width;for(let i=fallingTools.length-1;i>=0;i--){const tool=fallingTools[i];tool.y+=tool.speed;if(isCaught(tool)){score+=tool.score;scoreEl.textContent=score;fallingTools.splice(i,1);continue}if(tool.y>canvas.height+tool.size){lives--;livesEl.textContent=lives;fallingTools.splice(i,1);if(lives<=0){endGame();return}}}}
function isCaught(tool){const toolLeft=tool.x-tool.size/2,toolRight=tool.x+tool.size/2,toolBottom=tool.y+tool.size/2,playerLeft=player.x,playerRight=player.x+player.width,playerTop=player.y;return toolBottom>=playerTop&&toolRight>=playerLeft&&toolLeft<=playerRight}
function drawGame(){ctx.clearRect(0,0,canvas.width,canvas.height);drawStars();drawPlayer();drawFallingTools()}
function drawStars(){ctx.fillStyle="rgba(255, 255, 255, 0.25)";for(let i=0;i<50;i++){const x=i*137%canvas.width,y=i*91%canvas.height;ctx.fillRect(x,y,2,2)}}
function drawPlayer(){ctx.fillStyle="#00ffcc";ctx.shadowColor="#00ffcc";ctx.shadowBlur=15;ctx.fillRect(player.x,player.y,player.width,player.height);ctx.shadowBlur=0;ctx.fillStyle="#05070d";ctx.font="16px Arial";ctx.textAlign="center";ctx.fillText("CATCH",player.x+player.width/2,player.y+16);ctx.textAlign="left"}
function drawFallingTools(){fallingTools.forEach(tool=>{ctx.font=`${tool.size}px Arial`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(tool.icon,tool.x,tool.y)});ctx.textAlign="left";ctx.textBaseline="alphabetic"}
function endGame(){clearInterval(spawnTimer);cancelAnimationFrame(animationId);isPlaying=!1;const highestScore=Number(localStorage.getItem(HIGHEST_SCORE_KEY))||0;if(score>highestScore){localStorage.setItem(HIGHEST_SCORE_KEY,score);highestScoreEl.textContent=score;statusEl.textContent="New Highest Score!"}else statusEl.textContent="Game Over";ctx.fillStyle="rgba(0, 0, 0, 0.72)";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#ff6666";ctx.font="42px Arial";ctx.textAlign="center";ctx.fillText("GAME OVER",canvas.width/2,canvas.height/2-20);ctx.fillStyle="#00ffcc";ctx.font="22px Arial";ctx.fillText(`Final Score: ${score}`,canvas.width/2,canvas.height/2+25);ctx.textAlign="left"}
document.addEventListener("keydown",event=>{if(event.key==="ArrowLeft")player.moveLeft=!0;if(event.key==="ArrowRight")player.moveRight=!0});
document.addEventListener("keyup",event=>{if(event.key==="ArrowLeft")player.moveLeft=!1;if(event.key==="ArrowRight")player.moveRight=!1});
canvas.addEventListener("mousemove",event=>{const rect=canvas.getBoundingClientRect(),scaleX=canvas.width/rect.width,mouseX=(event.clientX-rect.left)*scaleX;player.x=mouseX-player.width/2;if(player.x<0)player.x=0;if(player.x+player.width>canvas.width)player.x=canvas.width-player.width});
startBtn.addEventListener("click",startGame);
restartBtn.addEventListener("click",restartGame);
loadTools().then(initGame);
