const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),scoreEl=document.getElementById("score"),blocksEl=document.getElementById("blocks"),highestScoreEl=document.getElementById("highestScore"),statusEl=document.getElementById("status"),startBtn=document.getElementById("startBtn"),dropBtn=document.getElementById("dropBtn"),restartBtn=document.getElementById("restartBtn"),HIGHEST_SCORE_KEY="websiteTowerHighestScore";let score=0,blocks=[],movingBlock=null,isPlaying=!1,animationId=null,cameraOffset=0,labels=[];const blockHeight=28,baseY=canvas.height-45,colors=["#00ccff","#00ff99","#ffcc00","#ff6699","#cc99ff","#ff8844"];highestScoreEl.textContent=localStorage.getItem(HIGHEST_SCORE_KEY)||0;
async function loadLabels(){try{const response=await fetch("./data/labels.json");labels=await response.json()}catch(error){statusEl.textContent="Failed to read labels.json";console.error(error)}}
function initGame(){score=0;blocks=[];cameraOffset=0;isPlaying=!1;const baseBlock={x:canvas.width/2-120,y:baseY,width:240,height:blockHeight,color:"#00ccff",label:"BASE"};blocks.push(baseBlock);scoreEl.textContent=score;blocksEl.textContent=0;statusEl.textContent="Ready";createMovingBlock();drawGame()}
function startGame(){if(!labels.length){statusEl.textContent="Label data is not available yet";return}if(isPlaying)return;isPlaying=!0;statusEl.textContent="Playing";gameLoop()}
function restartGame(){cancelAnimationFrame(animationId);initGame();startGame()}
function createMovingBlock(){const lastBlock=blocks[blocks.length-1];movingBlock={x:0,y:lastBlock.y-blockHeight-20,width:lastBlock.width,height:blockHeight,speed:3+Math.min(blocks.length*.18,5),direction:1,color:colors[Math.floor(Math.random()*colors.length)],label:labels[Math.floor(Math.random()*labels.length)]||"<div>"}}
function gameLoop(){updateGame();drawGame();if(isPlaying)animationId=requestAnimationFrame(gameLoop)}
function updateGame(){movingBlock.x+=movingBlock.speed*movingBlock.direction;if(movingBlock.x<=0){movingBlock.x=0;movingBlock.direction=1}if(movingBlock.x+movingBlock.width>=canvas.width){movingBlock.x=canvas.width-movingBlock.width;movingBlock.direction=-1}const towerTop=blocks[blocks.length-1].y,targetOffset=Math.max(0,canvas.height/2-towerTop);cameraOffset+=(targetOffset-cameraOffset)*.08}
function dropBlock(){if(!isPlaying||!movingBlock)return;const lastBlock=blocks[blocks.length-1],overlapLeft=Math.max(movingBlock.x,lastBlock.x),overlapRight=Math.min(movingBlock.x+movingBlock.width,lastBlock.x+lastBlock.width),overlapWidth=overlapRight-overlapLeft;if(overlapWidth<=0){endGame();return}const perfectMargin=Math.abs(movingBlock.x-lastBlock.x);let bonus=0;if(perfectMargin<=4){bonus=30;statusEl.textContent="Perfect!"}else if(perfectMargin<=15){bonus=15;statusEl.textContent="Great!"}else statusEl.textContent="Good";const newBlock={x:overlapLeft,y:lastBlock.y-blockHeight,width:overlapWidth,height:blockHeight,color:movingBlock.color,label:movingBlock.label};blocks.push(newBlock);const blockScore=Math.floor(overlapWidth/10)+bonus;score+=blockScore;scoreEl.textContent=score;blocksEl.textContent=blocks.length-1;if(overlapWidth<24){endGame();return}createMovingBlock()}
function drawGame(){ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();ctx.save();ctx.translate(0,cameraOffset);blocks.forEach(drawBlock);if(movingBlock)drawBlock(movingBlock);ctx.restore()}
function drawBackground(){ctx.fillStyle="rgba(255, 255, 255, 0.04)";for(let i=0;i<60;i++){const x=i*173%canvas.width,y=i*97%canvas.height;ctx.fillRect(x,y,2,2)}ctx.strokeStyle="rgba(0, 204, 255, 0.07)";ctx.lineWidth=1;for(let y=0;y<canvas.height;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}
function drawBlock(block){ctx.fillStyle=block.color;ctx.shadowColor=block.color;ctx.shadowBlur=12;ctx.fillRect(block.x,block.y,block.width,block.height);ctx.shadowBlur=0;ctx.strokeStyle="#ffffff";ctx.strokeRect(block.x,block.y,block.width,block.height);ctx.fillStyle="#05070d";ctx.font="bold 14px Arial";ctx.textAlign="center";ctx.textBaseline="middle";const text=block.width<55?"":block.label;ctx.fillText(text,block.x+block.width/2,block.y+block.height/2);ctx.textAlign="left";ctx.textBaseline="alphabetic"}
function endGame(){cancelAnimationFrame(animationId);isPlaying=!1;const highestScore=Number(localStorage.getItem(HIGHEST_SCORE_KEY))||0;if(score>highestScore){localStorage.setItem(HIGHEST_SCORE_KEY,score);highestScoreEl.textContent=score;statusEl.textContent="New Highest Score!"}else statusEl.textContent="Game Over";drawGame();ctx.fillStyle="rgba(0, 0, 0, 0.72)";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#ff6666";ctx.font="42px Arial";ctx.textAlign="center";ctx.fillText("GAME OVER",canvas.width/2,canvas.height/2-20);ctx.fillStyle="#00ccff";ctx.font="22px Arial";ctx.fillText(`Final Score: ${score}`,canvas.width/2,canvas.height/2+25);ctx.textAlign="left"}
document.addEventListener("keydown",event=>{if(event.code==="Space"){event.preventDefault();dropBlock()}});
startBtn.addEventListener("click",startGame);
dropBtn.addEventListener("click",dropBlock);
restartBtn.addEventListener("click",restartGame);
loadLabels().then(initGame);
